### ISSUE TITLE
Button component triggers Uncaught TypeError

### ISSUE THREAD

**Issue by fchpr** [TheComputerM/sapper-materialify-template#1]
### Steps to reproduce
```
git clone https://github.com/TheComputerM/sapper-materialify-template
cd sapper-materialify-template
npm install
npm run dev
```
Open browser console and then click on any button.
### Description
It seems to happen only on Sapper since it does not appear on the Svelte REPL for example.
### Error
```
material-ripple.js:48 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at RippleStart (material-ripple.js:48)
    at HTMLButtonElement.handleStart (index.js:11)
```

**Comment by TheComputerM** [comment]
It is not recommended that you use this template (for now anyways). Just follow the instructions at https://svelte-materialify.vercel.app/getting-started/installation/#advanced-install
